package fr.lewon.dofus.bot.handlers.movement

import fr.lewon.dofus.bot.sniffer.model.messages.move.MapComplementaryInformationsDataInHavenBagMessage

object MapComplementaryInformationsDataInHavenBagEventHandler :
    AbstractMapComplementaryInformationsDataEventHandler<MapComplementaryInformationsDataInHavenBagMessage>()